version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::448836841415:user/personal-github-actions"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::448836841415:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1CY2UGH4FK4DI"
cloudformation_execution_role = "arn:aws:iam::448836841415:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-4L344I24PAEA"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1ajydm2gdlohl"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::448836841415:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1CY2UGH4FK4DI"
cloudformation_execution_role = "arn:aws:iam::448836841415:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-4L344I24PAEA"
artifacts_bucket = ""
image_repository = ""
region = "us-east-1"
